import type { TodoTaskType } from "../types"

const today = new Date()
const tomorrow = new Date(today)
tomorrow.setDate(tomorrow.getDate() + 1)
const nextWeek = new Date(today)
nextWeek.setDate(nextWeek.getDate() + 7)
const yesterday = new Date(today)
yesterday.setDate(yesterday.getDate() - 1)

export const todosData: TodoTaskType[] = [
  {
    id: "todo-1",
    listId: "list-personal",
    order: 0,
    title: "Plan weekend trip",
    description: "Research destinations and book accommodation for the family.",
    completed: false,
    priority: "medium",
    dueDate: nextWeek,
    labels: [{ id: "label-1", name: "Personal", color: "bg-blue-500" }],
    createdAt: new Date(),
  },
  {
    id: "todo-2",
    listId: "list-work",
    order: 0,
    title: "Prepare quarterly report",
    description: "Compile Q1 data and create presentation slides.",
    completed: false,
    priority: "high",
    dueDate: today,
    labels: [{ id: "label-2", name: "Work", color: "bg-violet-500" }],
    createdAt: new Date(),
  },
  {
    id: "todo-3",
    listId: "list-shopping",
    order: 0,
    title: "Buy groceries",
    description: "Milk, eggs, bread, vegetables, and fruits.",
    completed: false,
    priority: "low",
    dueDate: today,
    labels: [{ id: "label-3", name: "Shopping", color: "bg-green-500" }],
    createdAt: new Date(),
  },
  {
    id: "todo-4",
    listId: "list-health",
    order: 0,
    title: "Schedule dentist appointment",
    completed: false,
    priority: "medium",
    dueDate: nextWeek,
    labels: [{ id: "label-4", name: "Health", color: "bg-red-500" }],
    createdAt: new Date(),
  },
  {
    id: "todo-5",
    listId: "list-work",
    order: 1,
    title: "Review pull requests",
    description: "Go through open PRs and leave feedback.",
    completed: false,
    priority: "high",
    dueDate: today,
    labels: [{ id: "label-2", name: "Work", color: "bg-violet-500" }],
    createdAt: new Date(),
  },
  {
    id: "todo-6",
    listId: "list-personal",
    order: 1,
    title: "Read chapter 5 of design patterns book",
    completed: true,
    priority: "low",
    labels: [{ id: "label-6", name: "Learning", color: "bg-orange-500" }],
    createdAt: new Date(),
  },
  {
    id: "todo-7",
    listId: "list-work",
    order: 2,
    title: "Update project documentation",
    description: "Add API reference and deployment guide.",
    completed: true,
    priority: "medium",
    dueDate: yesterday,
    labels: [{ id: "label-2", name: "Work", color: "bg-violet-500" }],
    createdAt: new Date(),
  },
  {
    id: "todo-8",
    listId: "list-shopping",
    order: 1,
    title: "Order new headphones",
    description: "Compare models and check reviews.",
    completed: false,
    priority: "low",
    dueDate: nextWeek,
    labels: [
      { id: "label-3", name: "Shopping", color: "bg-green-500" },
      { id: "label-5", name: "Finance", color: "bg-yellow-500" },
    ],
    createdAt: new Date(),
  },
  {
    id: "todo-9",
    listId: "list-health",
    order: 1,
    title: "Go for a 30-minute run",
    completed: false,
    priority: "none",
    dueDate: tomorrow,
    labels: [{ id: "label-4", name: "Health", color: "bg-red-500" }],
    createdAt: new Date(),
  },
  {
    id: "todo-10",
    listId: "list-personal",
    order: 2,
    title: "Pay electricity bill",
    completed: false,
    priority: "high",
    dueDate: tomorrow,
    labels: [{ id: "label-5", name: "Finance", color: "bg-yellow-500" }],
    createdAt: new Date(),
  },
  {
    id: "todo-11",
    listId: "list-work",
    order: 3,
    title: "Set up CI/CD pipeline",
    description:
      "Configure GitHub Actions for automated testing and deployment.",
    completed: false,
    priority: "medium",
    dueDate: nextWeek,
    labels: [{ id: "label-2", name: "Work", color: "bg-violet-500" }],
    createdAt: new Date(),
  },
  {
    id: "todo-12",
    listId: "list-personal",
    order: 3,
    title: "Organize photo library",
    completed: true,
    priority: "none",
    labels: [{ id: "label-1", name: "Personal", color: "bg-blue-500" }],
    createdAt: new Date(),
  },
]
