import type { ProductType } from "../../types"

export const productStatusesData = [
  { label: "All", value: "all" },
  { label: "In Stock", value: "In Stock" },
  { label: "Low Stock", value: "Low Stock" },
  { label: "Out of Stock", value: "Out of Stock" },
]

export const productsData: ProductType[] = [
  {
    id: "prod-001",
    name: "Bluetooth Headphones",
    sku: "BH-001",
    description:
      "Premium wireless bluetooth headphones with noise cancellation",
    category: "Audio",
    price: 4000,
    compareAtPrice: 4500,
    stock: 150,
    status: "In Stock",
    publishStatus: "Active",
    image: "/images/misc/product-01.jpg",
    tags: ["wireless", "audio", "bluetooth"],
  },
  {
    id: "prod-002",
    name: "Smartwatch",
    sku: "SW-002",
    description: "Feature-rich smartwatch with health monitoring",
    category: "Wearables",
    price: 8000,
    compareAtPrice: null,
    stock: 72,
    status: "In Stock",
    publishStatus: "Active",
    image: "/images/misc/product-02.jpg",
    tags: ["wearable", "fitness"],
  },
  {
    id: "prod-003",
    name: "Mirrorless Camera",
    sku: "MC-003",
    description: "Professional mirrorless camera with 4K video",
    category: "Cameras",
    price: 3000,
    compareAtPrice: 3500,
    stock: 5,
    status: "Low Stock",
    publishStatus: "Active",
    image: "/images/misc/product-03.jpg",
    tags: ["camera", "photography"],
  },
  {
    id: "prod-004",
    name: "Smartphone",
    sku: "SP-004",
    description: "Latest generation smartphone with advanced features",
    category: "Phones",
    price: 2000,
    compareAtPrice: null,
    stock: 0,
    status: "Out of Stock",
    publishStatus: "Active",
    image: "/images/misc/product-04.jpg",
    tags: ["phone", "mobile"],
  },
  {
    id: "prod-005",
    name: "Wireless Earbuds",
    sku: "WE-005",
    description: "Compact wireless earbuds with deep bass",
    category: "Audio",
    price: 1500,
    compareAtPrice: 1800,
    stock: 200,
    status: "In Stock",
    publishStatus: "Active",
    image: "/images/misc/product-01.jpg",
    tags: ["wireless", "audio"],
  },
  {
    id: "prod-006",
    name: "Fitness Tracker",
    sku: "FT-006",
    description: "Lightweight fitness tracker with heart rate monitor",
    category: "Wearables",
    price: 500,
    compareAtPrice: null,
    stock: 85,
    status: "In Stock",
    publishStatus: "Active",
    image: "/images/misc/product-02.jpg",
    tags: ["fitness", "wearable"],
  },
  {
    id: "prod-007",
    name: "Action Camera",
    sku: "AC-007",
    description: "Waterproof action camera for outdoor adventures",
    category: "Cameras",
    price: 4500,
    compareAtPrice: 5000,
    stock: 3,
    status: "Low Stock",
    publishStatus: "Active",
    image: "/images/misc/product-03.jpg",
    tags: ["camera", "waterproof"],
  },
  {
    id: "prod-008",
    name: "Tablet",
    sku: "TB-008",
    description: "High-performance tablet with retina display",
    category: "Electronics",
    price: 6000,
    compareAtPrice: null,
    stock: 45,
    status: "In Stock",
    publishStatus: "Active",
    image: "/images/misc/product-04.jpg",
    tags: ["tablet", "portable"],
  },
  {
    id: "prod-009",
    name: "Mechanical Keyboard",
    sku: "MK-009",
    description: "RGB mechanical keyboard with cherry switches",
    category: "Peripherals",
    price: 1200,
    compareAtPrice: 1400,
    stock: 0,
    status: "Out of Stock",
    publishStatus: "Draft",
    image: "/images/misc/product-01.jpg",
    tags: ["keyboard", "gaming"],
  },
  {
    id: "prod-010",
    name: "Gaming Mouse",
    sku: "GM-010",
    description: "Ergonomic gaming mouse with adjustable DPI",
    category: "Gaming",
    price: 800,
    compareAtPrice: null,
    stock: 120,
    status: "In Stock",
    publishStatus: "Active",
    image: "/images/misc/product-02.jpg",
    tags: ["gaming", "mouse"],
  },
  {
    id: "prod-011",
    name: "Portable SSD",
    sku: "PS-011",
    description: "1TB portable SSD with USB-C connectivity",
    category: "Storage",
    price: 1100,
    compareAtPrice: null,
    stock: 60,
    status: "In Stock",
    publishStatus: "Active",
    image: "/images/misc/product-03.jpg",
    tags: ["storage", "portable", "usb-c"],
  },
  {
    id: "prod-012",
    name: "Wi-Fi Router",
    sku: "WR-012",
    description: "Dual-band Wi-Fi 6 router for high-speed internet",
    category: "Networking",
    price: 2500,
    compareAtPrice: 2800,
    stock: 8,
    status: "Low Stock",
    publishStatus: "Active",
    image: "/images/misc/product-04.jpg",
    tags: ["networking", "wifi"],
  },
  {
    id: "prod-013",
    name: "USB-C Hub",
    sku: "UH-013",
    description: "7-in-1 USB-C hub with HDMI and ethernet",
    category: "Accessories",
    price: 450,
    compareAtPrice: null,
    stock: 300,
    status: "In Stock",
    publishStatus: "Active",
    image: "/images/misc/product-01.jpg",
    tags: ["usb-c", "accessories"],
  },
  {
    id: "prod-014",
    name: "Monitor Stand",
    sku: "MS-014",
    description: "Adjustable monitor stand with cable management",
    category: "Accessories",
    price: 350,
    compareAtPrice: 400,
    stock: 0,
    status: "Out of Stock",
    publishStatus: "Draft",
    image: "/images/misc/product-02.jpg",
    tags: ["accessories", "desk"],
  },
  {
    id: "prod-015",
    name: "Gaming Headset",
    sku: "GH-015",
    description: "Surround sound gaming headset with microphone",
    category: "Gaming",
    price: 900,
    compareAtPrice: null,
    stock: 95,
    status: "In Stock",
    publishStatus: "Active",
    image: "/images/misc/product-03.jpg",
    tags: ["gaming", "audio"],
  },
  {
    id: "prod-016",
    name: "Webcam HD",
    sku: "WC-016",
    description: "1080p webcam with auto-focus and noise reduction",
    category: "Peripherals",
    price: 700,
    compareAtPrice: 800,
    stock: 2,
    status: "Low Stock",
    publishStatus: "Active",
    image: "/images/misc/product-04.jpg",
    tags: ["webcam", "video"],
  },
  {
    id: "prod-017",
    name: "Power Bank",
    sku: "PB-017",
    description: "20000mAh power bank with fast charging",
    category: "Accessories",
    price: 350,
    compareAtPrice: null,
    stock: 180,
    status: "In Stock",
    publishStatus: "Active",
    image: "/images/misc/product-01.jpg",
    tags: ["portable", "charging"],
  },
  {
    id: "prod-018",
    name: "Smart Speaker",
    sku: "SS-018",
    description: "Voice-controlled smart speaker with premium sound",
    category: "Audio",
    price: 1800,
    compareAtPrice: 2000,
    stock: 0,
    status: "Out of Stock",
    publishStatus: "Active",
    image: "/images/misc/product-02.jpg",
    tags: ["audio", "smart-home"],
  },
]
