import type { OrderType } from "../../types"

export const paymentStatusesData = [
  { label: "All", value: "all" },
  { label: "Paid", value: "Paid" },
  { label: "Pending", value: "Pending" },
  { label: "Failed", value: "Failed" },
  { label: "Refunded", value: "Refunded" },
]

export const ordersData: OrderType[] = [
  {
    id: "ORD-1001",
    customerName: "John Doe",
    customerEmail: "john.doe@email.com",
    customerPhone: "+1 (555) 123-4567",
    shippingAddress: "123 Main St, New York, NY 10001",
    orderDate: "2024-11-01T10:00:00Z",
    totalAmount: 270,
    paymentStatus: "Paid",
    deliveryStatus: "Delivered",
    items: [
      {
        productName: "Bluetooth Headphones",
        productImage: "/images/misc/product-01.jpg",
        sku: "BH-001",
        quantity: 1,
        unitPrice: 150,
      },
      {
        productName: "Wireless Earbuds",
        productImage: "/images/misc/product-02.jpg",
        sku: "WE-005",
        quantity: 1,
        unitPrice: 100,
      },
    ],
    timeline: [
      {
        status: "Order Placed",
        date: "2024-11-01T10:00:00Z",
        description: "Order was placed by customer",
      },
      {
        status: "Confirmed",
        date: "2024-11-01T10:30:00Z",
        description: "Payment confirmed",
      },
      {
        status: "Shipped",
        date: "2024-11-03T14:00:00Z",
        description: "Package shipped via express delivery",
      },
      {
        status: "Delivered",
        date: "2024-11-05T09:15:00Z",
        description: "Package delivered to customer",
      },
    ],
  },
  {
    id: "ORD-1002",
    customerName: "Emily Smith",
    customerEmail: "emily.smith@email.com",
    customerPhone: "+1 (555) 234-5678",
    shippingAddress: "456 Oak Ave, Los Angeles, CA 90001",
    orderDate: "2024-11-03T14:30:00Z",
    totalAmount: 8640,
    paymentStatus: "Paid",
    deliveryStatus: "Shipped",
    items: [
      {
        productName: "Smartwatch",
        productImage: "/images/misc/product-02.jpg",
        sku: "SW-002",
        quantity: 1,
        unitPrice: 8000,
      },
    ],
    timeline: [
      {
        status: "Order Placed",
        date: "2024-11-03T14:30:00Z",
        description: "Order was placed by customer",
      },
      {
        status: "Confirmed",
        date: "2024-11-03T15:00:00Z",
        description: "Payment confirmed",
      },
      {
        status: "Shipped",
        date: "2024-11-05T10:00:00Z",
        description: "Package shipped",
      },
    ],
  },
  {
    id: "ORD-1003",
    customerName: "Michael Brown",
    customerEmail: "m.brown@email.com",
    customerPhone: "+1 (555) 345-6789",
    shippingAddress: "789 Pine Rd, Chicago, IL 60601",
    orderDate: "2024-11-05T09:00:00Z",
    totalAmount: 3240,
    paymentStatus: "Pending",
    deliveryStatus: "Processing",
    items: [
      {
        productName: "Mirrorless Camera",
        productImage: "/images/misc/product-03.jpg",
        sku: "MC-003",
        quantity: 1,
        unitPrice: 3000,
      },
    ],
    timeline: [
      {
        status: "Order Placed",
        date: "2024-11-05T09:00:00Z",
        description: "Order was placed by customer",
      },
      {
        status: "Processing",
        date: "2024-11-05T09:15:00Z",
        description: "Awaiting payment confirmation",
      },
    ],
  },
  {
    id: "ORD-1004",
    customerName: "Sarah Johnson",
    customerEmail: "sarah.j@email.com",
    customerPhone: "+1 (555) 456-7890",
    shippingAddress: "321 Elm St, Houston, TX 77001",
    orderDate: "2024-11-07T11:00:00Z",
    totalAmount: 2160,
    paymentStatus: "Paid",
    deliveryStatus: "In Transit",
    items: [
      {
        productName: "Smartphone",
        productImage: "/images/misc/product-04.jpg",
        sku: "SP-004",
        quantity: 1,
        unitPrice: 2000,
      },
    ],
    timeline: [
      {
        status: "Order Placed",
        date: "2024-11-07T11:00:00Z",
        description: "Order was placed by customer",
      },
      {
        status: "Confirmed",
        date: "2024-11-07T11:30:00Z",
        description: "Payment confirmed",
      },
      {
        status: "Shipped",
        date: "2024-11-09T08:00:00Z",
        description: "Package shipped",
      },
      {
        status: "In Transit",
        date: "2024-11-10T12:00:00Z",
        description: "Package in transit to destination",
      },
    ],
  },
  {
    id: "ORD-1005",
    customerName: "David Wilson",
    customerEmail: "d.wilson@email.com",
    customerPhone: "+1 (555) 567-8901",
    shippingAddress: "654 Maple Dr, Phoenix, AZ 85001",
    orderDate: "2024-11-08T16:00:00Z",
    totalAmount: 540,
    paymentStatus: "Failed",
    deliveryStatus: "Pending",
    items: [
      {
        productName: "USB-C Hub",
        productImage: "/images/misc/product-01.jpg",
        sku: "UH-013",
        quantity: 1,
        unitPrice: 500,
      },
    ],
    timeline: [
      {
        status: "Order Placed",
        date: "2024-11-08T16:00:00Z",
        description: "Order was placed by customer",
      },
      {
        status: "Payment Failed",
        date: "2024-11-08T16:05:00Z",
        description: "Payment method declined",
      },
    ],
  },
  {
    id: "ORD-1006",
    customerName: "Olivia Martinez",
    customerEmail: "olivia.m@email.com",
    customerPhone: "+1 (555) 678-9012",
    shippingAddress: "987 Cedar Ln, Philadelphia, PA 19101",
    orderDate: "2024-11-10T13:00:00Z",
    totalAmount: 1944,
    paymentStatus: "Paid",
    deliveryStatus: "Delivered",
    items: [
      {
        productName: "Mechanical Keyboard",
        productImage: "/images/misc/product-03.jpg",
        sku: "MK-009",
        quantity: 1,
        unitPrice: 1200,
      },
      {
        productName: "Gaming Mouse",
        productImage: "/images/misc/product-04.jpg",
        sku: "GM-010",
        quantity: 1,
        unitPrice: 600,
      },
    ],
    timeline: [
      {
        status: "Order Placed",
        date: "2024-11-10T13:00:00Z",
        description: "Order was placed by customer",
      },
      {
        status: "Confirmed",
        date: "2024-11-10T13:30:00Z",
        description: "Payment confirmed",
      },
      {
        status: "Shipped",
        date: "2024-11-12T09:00:00Z",
        description: "Package shipped",
      },
      {
        status: "Delivered",
        date: "2024-11-14T11:00:00Z",
        description: "Package delivered",
      },
    ],
  },
  {
    id: "ORD-1007",
    customerName: "James Anderson",
    customerEmail: "james.a@email.com",
    customerPhone: "+1 (555) 789-0123",
    shippingAddress: "147 Birch St, San Antonio, TX 78201",
    orderDate: "2024-11-12T10:00:00Z",
    totalAmount: 1620,
    paymentStatus: "Refunded",
    deliveryStatus: "Delivered",
    items: [
      {
        productName: "Wireless Earbuds",
        productImage: "/images/misc/product-01.jpg",
        sku: "WE-005",
        quantity: 1,
        unitPrice: 1500,
      },
    ],
    timeline: [
      {
        status: "Order Placed",
        date: "2024-11-12T10:00:00Z",
        description: "Order was placed by customer",
      },
      {
        status: "Confirmed",
        date: "2024-11-12T10:30:00Z",
        description: "Payment confirmed",
      },
      {
        status: "Shipped",
        date: "2024-11-14T08:00:00Z",
        description: "Package shipped",
      },
      {
        status: "Delivered",
        date: "2024-11-16T10:00:00Z",
        description: "Package delivered",
      },
      {
        status: "Refunded",
        date: "2024-11-18T14:00:00Z",
        description: "Customer requested refund — product returned",
      },
    ],
  },
  {
    id: "ORD-1008",
    customerName: "Sophia Taylor",
    customerEmail: "sophia.t@email.com",
    customerPhone: "+1 (555) 890-1234",
    shippingAddress: "258 Walnut Ave, San Diego, CA 92101",
    orderDate: "2024-11-14T15:00:00Z",
    totalAmount: 1188,
    paymentStatus: "Paid",
    deliveryStatus: "Delivered",
    items: [
      {
        productName: "Portable SSD",
        productImage: "/images/misc/product-03.jpg",
        sku: "PS-011",
        quantity: 1,
        unitPrice: 1100,
      },
    ],
    timeline: [
      {
        status: "Order Placed",
        date: "2024-11-14T15:00:00Z",
        description: "Order was placed by customer",
      },
      {
        status: "Confirmed",
        date: "2024-11-14T15:30:00Z",
        description: "Payment confirmed",
      },
      {
        status: "Shipped",
        date: "2024-11-16T09:00:00Z",
        description: "Package shipped",
      },
      {
        status: "Delivered",
        date: "2024-11-18T10:00:00Z",
        description: "Package delivered",
      },
    ],
  },
  {
    id: "ORD-1009",
    customerName: "Daniel Thomas",
    customerEmail: "daniel.t@email.com",
    customerPhone: "+1 (555) 901-2345",
    shippingAddress: "369 Spruce Ct, Dallas, TX 75201",
    orderDate: "2024-11-16T12:00:00Z",
    totalAmount: 4860,
    paymentStatus: "Paid",
    deliveryStatus: "Shipped",
    items: [
      {
        productName: "Action Camera",
        productImage: "/images/misc/product-03.jpg",
        sku: "AC-007",
        quantity: 1,
        unitPrice: 4500,
      },
    ],
    timeline: [
      {
        status: "Order Placed",
        date: "2024-11-16T12:00:00Z",
        description: "Order was placed by customer",
      },
      {
        status: "Confirmed",
        date: "2024-11-16T12:30:00Z",
        description: "Payment confirmed",
      },
      {
        status: "Shipped",
        date: "2024-11-18T10:00:00Z",
        description: "Package shipped via standard delivery",
      },
    ],
  },
  {
    id: "ORD-1010",
    customerName: "Isabella Garcia",
    customerEmail: "isabella.g@email.com",
    customerPhone: "+1 (555) 012-3456",
    shippingAddress: "480 Ash Blvd, San Jose, CA 95101",
    orderDate: "2024-11-18T09:00:00Z",
    totalAmount: 378,
    paymentStatus: "Pending",
    deliveryStatus: "Pending",
    items: [
      {
        productName: "Power Bank",
        productImage: "/images/misc/product-01.jpg",
        sku: "PB-017",
        quantity: 1,
        unitPrice: 350,
      },
    ],
    timeline: [
      {
        status: "Order Placed",
        date: "2024-11-18T09:00:00Z",
        description: "Order was placed by customer",
      },
    ],
  },
  {
    id: "ORD-1011",
    customerName: "William Lee",
    customerEmail: "w.lee@email.com",
    customerPhone: "+1 (555) 111-2222",
    shippingAddress: "591 Willow Way, Austin, TX 73301",
    orderDate: "2024-11-19T14:00:00Z",
    totalAmount: 6480,
    paymentStatus: "Paid",
    deliveryStatus: "Delivered",
    items: [
      {
        productName: "Tablet",
        productImage: "/images/misc/product-04.jpg",
        sku: "TB-008",
        quantity: 1,
        unitPrice: 6000,
      },
    ],
    timeline: [
      {
        status: "Order Placed",
        date: "2024-11-19T14:00:00Z",
        description: "Order was placed by customer",
      },
      {
        status: "Confirmed",
        date: "2024-11-19T14:30:00Z",
        description: "Payment confirmed",
      },
      {
        status: "Shipped",
        date: "2024-11-21T08:00:00Z",
        description: "Package shipped",
      },
      {
        status: "Delivered",
        date: "2024-11-23T10:00:00Z",
        description: "Package delivered",
      },
    ],
  },
  {
    id: "ORD-1012",
    customerName: "Mia Harris",
    customerEmail: "mia.h@email.com",
    customerPhone: "+1 (555) 222-3333",
    shippingAddress: "702 Poplar Dr, Jacksonville, FL 32099",
    orderDate: "2024-11-20T11:00:00Z",
    totalAmount: 2700,
    paymentStatus: "Failed",
    deliveryStatus: "Pending",
    items: [
      {
        productName: "Wi-Fi Router",
        productImage: "/images/misc/product-04.jpg",
        sku: "WR-012",
        quantity: 1,
        unitPrice: 2500,
      },
    ],
    timeline: [
      {
        status: "Order Placed",
        date: "2024-11-20T11:00:00Z",
        description: "Order was placed by customer",
      },
      {
        status: "Payment Failed",
        date: "2024-11-20T11:05:00Z",
        description: "Insufficient funds",
      },
    ],
  },
  {
    id: "ORD-1013",
    customerName: "Ethan Clark",
    customerEmail: "ethan.c@email.com",
    customerPhone: "+1 (555) 333-4444",
    shippingAddress: "813 Aspen Rd, Columbus, OH 43004",
    orderDate: "2024-11-22T16:00:00Z",
    totalAmount: 972,
    paymentStatus: "Paid",
    deliveryStatus: "In Transit",
    items: [
      {
        productName: "Gaming Headset",
        productImage: "/images/misc/product-03.jpg",
        sku: "GH-015",
        quantity: 1,
        unitPrice: 900,
      },
    ],
    timeline: [
      {
        status: "Order Placed",
        date: "2024-11-22T16:00:00Z",
        description: "Order was placed by customer",
      },
      {
        status: "Confirmed",
        date: "2024-11-22T16:30:00Z",
        description: "Payment confirmed",
      },
      {
        status: "Shipped",
        date: "2024-11-24T09:00:00Z",
        description: "Package shipped",
      },
      {
        status: "In Transit",
        date: "2024-11-25T12:00:00Z",
        description: "Package in transit",
      },
    ],
  },
  {
    id: "ORD-1014",
    customerName: "Charlotte Lewis",
    customerEmail: "charlotte.l@email.com",
    customerPhone: "+1 (555) 444-5555",
    shippingAddress: "924 Chestnut Pl, Fort Worth, TX 76101",
    orderDate: "2024-11-24T10:00:00Z",
    totalAmount: 756,
    paymentStatus: "Paid",
    deliveryStatus: "Processing",
    items: [
      {
        productName: "Webcam HD",
        productImage: "/images/misc/product-04.jpg",
        sku: "WC-016",
        quantity: 1,
        unitPrice: 700,
      },
    ],
    timeline: [
      {
        status: "Order Placed",
        date: "2024-11-24T10:00:00Z",
        description: "Order was placed by customer",
      },
      {
        status: "Confirmed",
        date: "2024-11-24T10:30:00Z",
        description: "Payment confirmed",
      },
      {
        status: "Processing",
        date: "2024-11-24T11:00:00Z",
        description: "Order is being prepared",
      },
    ],
  },
  {
    id: "ORD-1015",
    customerName: "Alexander Walker",
    customerEmail: "alex.w@email.com",
    customerPhone: "+1 (555) 555-6666",
    shippingAddress: "135 Magnolia Ln, Charlotte, NC 28201",
    orderDate: "2024-11-25T13:00:00Z",
    totalAmount: 1944,
    paymentStatus: "Refunded",
    deliveryStatus: "Delivered",
    items: [
      {
        productName: "Smart Speaker",
        productImage: "/images/misc/product-02.jpg",
        sku: "SS-018",
        quantity: 1,
        unitPrice: 1800,
      },
    ],
    timeline: [
      {
        status: "Order Placed",
        date: "2024-11-25T13:00:00Z",
        description: "Order was placed by customer",
      },
      {
        status: "Confirmed",
        date: "2024-11-25T13:30:00Z",
        description: "Payment confirmed",
      },
      {
        status: "Shipped",
        date: "2024-11-27T09:00:00Z",
        description: "Package shipped",
      },
      {
        status: "Delivered",
        date: "2024-11-29T11:00:00Z",
        description: "Package delivered",
      },
      {
        status: "Refunded",
        date: "2024-12-01T10:00:00Z",
        description: "Refund processed — defective item",
      },
    ],
  },
  {
    id: "ORD-1016",
    customerName: "Amelia Young",
    customerEmail: "amelia.y@email.com",
    customerPhone: "+1 (555) 666-7777",
    shippingAddress: "246 Dogwood St, Indianapolis, IN 46201",
    orderDate: "2024-11-27T09:00:00Z",
    totalAmount: 2862,
    paymentStatus: "Paid",
    deliveryStatus: "Delivered",
    items: [
      {
        productName: "Fitness Tracker",
        productImage: "/images/misc/product-02.jpg",
        sku: "FT-006",
        quantity: 2,
        unitPrice: 500,
      },
      {
        productName: "Bluetooth Headphones",
        productImage: "/images/misc/product-01.jpg",
        sku: "BH-001",
        quantity: 1,
        unitPrice: 1650,
      },
    ],
    timeline: [
      {
        status: "Order Placed",
        date: "2024-11-27T09:00:00Z",
        description: "Order was placed by customer",
      },
      {
        status: "Confirmed",
        date: "2024-11-27T09:30:00Z",
        description: "Payment confirmed",
      },
      {
        status: "Shipped",
        date: "2024-11-29T08:00:00Z",
        description: "Package shipped",
      },
      {
        status: "Delivered",
        date: "2024-12-01T10:00:00Z",
        description: "Package delivered",
      },
    ],
  },
  {
    id: "ORD-1017",
    customerName: "Benjamin King",
    customerEmail: "ben.k@email.com",
    customerPhone: "+1 (555) 777-8888",
    shippingAddress: "357 Juniper Ave, San Francisco, CA 94101",
    orderDate: "2024-11-29T15:00:00Z",
    totalAmount: 540,
    paymentStatus: "Pending",
    deliveryStatus: "Pending",
    items: [
      {
        productName: "Monitor Stand",
        productImage: "/images/misc/product-02.jpg",
        sku: "MS-014",
        quantity: 1,
        unitPrice: 500,
      },
    ],
    timeline: [
      {
        status: "Order Placed",
        date: "2024-11-29T15:00:00Z",
        description: "Order was placed by customer",
      },
    ],
  },
  {
    id: "ORD-1018",
    customerName: "Harper Wright",
    customerEmail: "harper.w@email.com",
    customerPhone: "+1 (555) 888-9999",
    shippingAddress: "468 Cypress Rd, Seattle, WA 98101",
    orderDate: "2024-12-01T10:00:00Z",
    totalAmount: 4320,
    paymentStatus: "Paid",
    deliveryStatus: "Shipped",
    items: [
      {
        productName: "Mirrorless Camera",
        productImage: "/images/misc/product-03.jpg",
        sku: "MC-003",
        quantity: 1,
        unitPrice: 3000,
      },
      {
        productName: "Portable SSD",
        productImage: "/images/misc/product-03.jpg",
        sku: "PS-011",
        quantity: 1,
        unitPrice: 1000,
      },
    ],
    timeline: [
      {
        status: "Order Placed",
        date: "2024-12-01T10:00:00Z",
        description: "Order was placed by customer",
      },
      {
        status: "Confirmed",
        date: "2024-12-01T10:30:00Z",
        description: "Payment confirmed",
      },
      {
        status: "Shipped",
        date: "2024-12-03T09:00:00Z",
        description: "Package shipped",
      },
    ],
  },
  {
    id: "ORD-1019",
    customerName: "Lucas Scott",
    customerEmail: "lucas.s@email.com",
    customerPhone: "+1 (555) 999-0000",
    shippingAddress: "579 Redwood Blvd, Denver, CO 80201",
    orderDate: "2024-12-03T12:00:00Z",
    totalAmount: 864,
    paymentStatus: "Failed",
    deliveryStatus: "Pending",
    items: [
      {
        productName: "Gaming Mouse",
        productImage: "/images/misc/product-04.jpg",
        sku: "GM-010",
        quantity: 1,
        unitPrice: 800,
      },
    ],
    timeline: [
      {
        status: "Order Placed",
        date: "2024-12-03T12:00:00Z",
        description: "Order was placed by customer",
      },
      {
        status: "Payment Failed",
        date: "2024-12-03T12:05:00Z",
        description: "Card expired",
      },
    ],
  },
  {
    id: "ORD-1020",
    customerName: "Ella Adams",
    customerEmail: "ella.a@email.com",
    customerPhone: "+1 (555) 000-1111",
    shippingAddress: "690 Sycamore Dr, Nashville, TN 37201",
    orderDate: "2024-12-05T14:00:00Z",
    totalAmount: 486,
    paymentStatus: "Pending",
    deliveryStatus: "Processing",
    items: [
      {
        productName: "USB-C Hub",
        productImage: "/images/misc/product-01.jpg",
        sku: "UH-013",
        quantity: 1,
        unitPrice: 450,
      },
    ],
    timeline: [
      {
        status: "Order Placed",
        date: "2024-12-05T14:00:00Z",
        description: "Order was placed by customer",
      },
      {
        status: "Processing",
        date: "2024-12-05T14:15:00Z",
        description: "Awaiting payment confirmation",
      },
    ],
  },
]
